### ISSUE TITLE
Sidenotes

### ISSUE THREAD

**Issue by minchinweb** [MinchinWeb/blog.minchin.ca#130]
I like the idea of have endnotes and footnotes as *sidenotes*, that appear in the column beside the main body of the article.

Issues include what to do on smaller screens.

One example --> https://wejn.org/2021/12/rethinking-number-formatting/

**Comment by minchinweb** [comment]
Another implementation --> [Magick.css](https://css.winterveil.net/)

**Comment by minchinweb** [comment]
Another beautiful implementation.  https://khz.ac/sound/ribbon-mic/

Also, the CSS seems very simple, so I'll include most of it here

```css
@import url("attr.css");

// [removed font definitions]

:root {
	font-family: baskervaldx, serif;
	font-variant-numeric: oldstyle-nums proportional-nums;
	font-size: 1.1rem;
}

body {
	display: flex;
	flex-direction: column;
	min-height: 93vh;
}

header {
	margin: auto;
	text-align: center;
}

main {
	flex-grow: 1;
	margin: auto;
	padding: 0 2em;
	max-width: 30em;
	text-align: justify;
	text-justify: inter-word;
	line-height: 1.3;
}

footer {
	position: relative;
	margin: 3rem auto 1rem;
	font-size: 60%;
}

h1, h2, h3, h4, h5, h6 {
	font-weight: normal;
}

h2, h3, h4, h5, h6 {
	padding-left: 2rem;
}

sup {
	font-size: 60%;
}


figure {
	text-align: center;

	figcaption {
		margin: auto;
		max-width: 80%;
		font-size: smaller;
	}

	img {
		margin: auto;
		max-width: 100%;
		max-height: 28em;
		border: 0.2rem solid gray;
	}

}

math {
	font-family: inherit;
	font-variant-numeric: lining-nums proportional-nums;
	margin: 0.5em auto;
}

.banner {
	position: relative;
	margin: 2rem auto 0;
	font-size: 400%;
	display: flex;
	flex-direction: row;
	justify-content: center;
	font-style: italic;
}

.head-rule {
	margin: 1rem -2rem 2rem;
}

.tabular {
	font-variant-numeric: tabular-nums;
}

sc {
	font-variant: small-caps;
}

/* partly from https://scripter.co/sidenotes-using-only-css/,
   partly from https://github.com/edwardtufte/tufte-css,
   partly just figured out */

.sidenote, .margin-note {
	small {
		font-size: 80%;
		position: relative;
	}
}

@media (min-width: 73rem) {
	.sidenote, .margin-note {
		small {
			width: 16rem;
			margin-top: 1rem;
		}
	}

	/* alternate left and right notes */
	.sidenote:nth-of-type(even), .margin-note:nth-of-type(even) {
		small {
			margin-right: -18rem;
			float: right;
			clear: right;
			text-align: left;
		}
	}

	.sidenote:nth-of-type(odd), .margin-note:nth-of-type(odd) {
		small {
			margin-left: -18rem;
			float: left;
			clear: left;
			text-align: right;
		}
	}
}

@media (max-width: 73rem) {
	.sidenote, .margin-note {
		small {
			float: left;
			text-align: left;

			width: 86%;
			margin: 0.5rem 0;
			margin-left: 10%;
			padding-left: 4%;

			border-left-style: solid;
			border-width: 0.13rem;
			border-color: gray;
		}
	}
}

.sidenote, .margin-note {
	small::before {
		position: relative;
		vertical-align: baseline;
	}
}

.sidenote::after, .margin-note::after {
	vertical-align: super;
}

/* set up counters for sidenotes only */
body {
	counter-set: sidenote-counter -1;
}

.sidenote {
	counter-increment: sidenote-counter;
}

.sidenote small::before {
	content: counter(sidenote-counter)".";
	font-weight: bold;
}

.sidenote::after {
	content: counter(sidenote-counter);
	font-size: 60%;
	font-weight: bold;
	margin-right: 0.3em;
}

/* table of contents formatting */
.toc-list {
	list-style-type: none;
	font-size: larger;
}

.toc-list ol {
	list-style-type: none;
	padding-inline-start: 2rem;
	font-size: smaller;
}
```

**Comment by minchinweb** [comment]
Another implementation: The Obsidian Sancum Reborn theme, using the `<aside>` element.

https://github.com/antoKeinanen/obsidian-sanctum-reborn/blob/main/documentation/Theme_Guide.md

**Comment by minchinweb** [comment]
Another Obsidian plugin --> https://github.com/xhuajin/obsidian-sidenote-callout

**Comment by minchinweb** [comment]
A rather simple (and working) implementation (from 2019): https://kennethfriedman.org/thoughts/2019/marginal-notes/

Sample code (including CSS):

```html
<!DOCTYPE html>
<html lang="en">
 <head>
  <title>KF: Marginal Note Example</title>
  <style>
   main {
    max-width: 500px; /*provides maximum, in case screen is huge*/
    width: 60%;   /*keeps body text width reasonable*/
    margin: 0 auto;  /*centers main on page*/
   }
   
   /*Marginal Notes on Desktop*/
   aside, .aside {
    display: inline;
    float: right;
    position: relative;
    width: 20vw;
    margin-right: -24vw;
    font-size: 16px;
    color:red;
   }
   
   /*Marginal Notes on mobile*/
   @media (max-width: 768px) {
    aside, .aside {
     display: block;
     float: none;
     margin: 5% 10% 5% 10%;
     width: 80%;
     font-size: 15px;
     color:red;
    }
   }
  </style>
 </head>
 <body>
  <main>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et sodales neque. Suspendisse rhoncus ut risus sit amet malesuada. Proin eu tincidunt ex, eu efficitur mauris. Nam sollicitudin finibus mi. Phasellus auctor mattis diam, non pulvinar sem egestas at. Pellentesque ultricies mi eu mi ultrices, at semper nibh lobortis. Pellentesque eros purus, euismod viverra metus vitae, laoreet vehicula risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque vitae maximus orci. Nulla vitae laoreet elit. Fusce at turpis tincidunt, scelerisque justo non, tristique enim.</p>
   <p>Maecenas faucibus sed justo eget fringilla. Nullam feugiat laoreet felis id convallis. <span class="aside">This is a marginal note using a <em>span</em> tag</span> Curabitur accumsan pulvinar magna ut egestas. Aenean sed purus fringilla purus dapibus pharetra sit amet quis dolor. Aenean vitae elit ante. Cras fermentum nulla a imperdiet efficitur. Fusce dignissim risus nulla, sit amet hendrerit libero ultricies eleifend.</p>
   <p>Morbi sed condimentum arcu. Duis eros tellus, elementum et leo facilisis, facilisis finibus lorem. Suspendisse suscipit ultrices sollicitudin. Nulla gravida eget nulla ut bibendum. Donec faucibus congue ante nec sollicitudin. Fusce a maximus urna. Etiam eu viverra nibh. Suspendisse molestie enim ex, nec pulvinar sapien rutrum sed. Curabitur eu mattis libero. In sed efficitur elit, congue placerat sapien. Proin fringilla est at erat tempus, ac commodo leo ullamcorper. Nunc nec ante viverra, euismod nulla ac, ultrices est. Pellentesque vel finibus massa, at tincidunt ligula. Vivamus in metus a diam consequat aliquam.</p>
   <p>Suspendisse varius consequat ullamcorper. Vivamus neque urna, dapibus vel placerat at, pretium non odio. <aside>This is a marginal note using the semantic <em>aside</em> tag.</aside>Proin molestie porta malesuada. Duis tristique luctus lacus ut rutrum. Sed lacus elit, lacinia imperdiet iaculis vel, viverra sed dolor. Integer tempus augue hendrerit condimentum egestas. Ut aliquam varius rutrum. Curabitur tempus enim ut libero vehicula, non rutrum justo ornare. Cras nisl nibh, suscipit convallis nulla non, egestas laoreet justo. Sed fringilla ligula eu elit luctus, non eleifend magna placerat.</p>
   <p>Demo of Marginal Notes by <a href="http://kennethfriedman.org">Kenneth Friedman</a>.</p>
  </main>
 </body>
</html> 
```

**Comment by minchinweb** [comment]
Another implementation --> https://www.scottsmitelli.com/articles/take-oncall-and-shove-it/

This is explicitly based on [Tufte CSS](https://edwardtufte.github.io/tufte-css/) (c.f. [here](https://www.scottsmitelli.com/projects/scottsmitelli.com/))

His whole stylesheet isn't that involved, although the base one seems to be [written in SASS](https://github.com/smitelli/scottsmitelli.com/tree/master/src/assets/scss)

He is also the sidebar space for the published date and the Table of Contents for the page. And sometimes other metadata.

**Comment by minchinweb** [comment]
[Alex Beal's blog](https://blog.alexbeals.com/posts/remove-unused-characters-font-size) has an implementation. Under the hood, the text of the sidenote is immediately after the sidenote/footnote reference. The sidenotes are displayed on wide enough monitors (i.e. not on mobile). He also keeps the same text as a footnote, and displays that at all times as well.

It looks like he also puts sidenotes on alternating sides of the page.

<img width="411" height="148" alt="Image" src="https://github.com/user-attachments/assets/67f2faa0-5eef-4660-a317-871748f3a80b" />

Inline sidenote:

```html
<p>
    This font file was 160kB though, even though I only needed two glyphs. You can shrink font files using <code>pyftsubset</code>
    <span class="sidenote-wrapper" role="note">
        <sup class="sidenote-indicator" id="fnref1:pyft">1</sup>
        <span class="sidenote" data-footnote-index="1">
            <span class="text">
                <code>brew install fonttools</code> if you don't have it, and if you don't have <code>brew</code> then the <a href="https://github.com/fonttools/fonttools" class="inline" target="_blank">GitHub</a> has install instructions.
            </span>
        </span>
    </span>
    to just the Unicode codepoints you need. In this case the command got the file from 160kB down to 680 bytes, a 99.5% savings:
</p>
```

and the bits of CSS:

```css
sup {
  top:-.5em
}

/** Sidenotes */
.sidenote-indicator {
  margin-left: -3px;
}
.sidenote {
  float: right;
  clear: right;
  text-align: left;
  --gutter-width: calc((100vw - var(--container-width) + var(--container-padding) * 2) / 2);
  --sidenote-width: calc(var(--gutter-width) - var(--content-padding) - var(--outside-padding));
  width: min(var(--sidenote-max-width), var(--sidenote-width));
  font-size: 0.9em;
  line-height: 1.3;
  --margin: max(
    calc(-1 * (var(--sidenote-max-width) + var(--content-padding))),
    calc(-1 * (var(--sidenote-width) + var(--content-padding)))
  );
  margin-right: var(--margin);
  color: var(--secondary-text);
  white-space: nowrap;
  margin-bottom: 15px;
}
.sidenote .text {
  white-space: normal;
}
.sidenote img, .sidenote video {
  margin-top: 5px;
  margin-bottom: 5px;
}
.even-sidenote {
  float: left;
  clear: left;
  margin-right: 0;
  margin-left: var(--margin);
  text-align: right;
  padding-left: 20px;
}
.sidenote::before {
  content: attr(data-footnote-index) " ";
  left: -0.2em;
  top: -0.3em;
  font-size: 0.9em;
  position: relative;
}
blockquote .sidenote-wrapper {
  font-size: 20px;
  /* In case it's inside an italicized quote */
  font-style: normal;
}
blockquote .sidenote {
  margin-right: calc(var(--margin) - 20px);
}
blockquote .even-sidenote {
  margin-left: calc(var(--margin) - 20px - 5px); /* has to account for 5px green line on blockquote */
}
li .even-sidenote {
  margin-left: calc(var(--margin) - 20px - 20px); /* has to account for indent on list */
}
/* Footnotes corresponding with sidenotes */
.footnotes img {
  max-height: 200px;
  max-width: 200px;
  display: block;
  margin: 0;
}
.footnotes li > p {
  /* Makes sure the line marker works with photos and videos */
  display: inline-block;
  vertical-align: top;
}
```
